improve scripts

diff --git a/scripts/ci/test-pr b/scripts/ci/test-pr
--- a/scripts/ci/test-pr
+++ b/scripts/ci/test-pr
@@ -14,24 +14,39 @@ done
 
 # Relative path to the dir containing operator manifests. Usually something
 # like "community-operators/automation-broker".
-REL_OP_PATH="$1"
+[[ -z "$REL_OP_PATH" ]] && REL_OP_PATH="$1"
 if [[ ! -d "$REL_OP_PATH" ]]; then
   echo "Relative path to operator package '$REL_OP_PATH' does not exist."
   exit 1
 fi
 # This script assumes versions are written as "v0.0.1" in file names and
 # fields, but OP_VER is expected to not include a "v" prefix, ex. "0.0.1".
-OP_VER="$2"
+[[ -z "$OP_VER" ]] && OP_VER="$2"
 if [[ -z "$OP_VER" || ! "$OP_VER" =~ ^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$ ]]; then
   echo "Operator version '$OP_VER' not valid."
   exit 1
 fi
 
-if [[ -z "$KUBECONFIG" ]]; then
-  echo "KUBECONFIG not set"
+if [[ -z "$CLUSTER_NAME" ]]; then
+  echo "CLUSTER_NAME not set."
   exit 1
 fi
-oc config use-context
+[[ -z "$KUBECONFIG" ]] && KUBECONFIG="$(pwd)/${CLUSTER_NAME}/auth/kubeconfig"
+if [[ ! -e "$KUBECONFIG" ]]; then
+  echo "KUBECONFIG does not exist."
+  exit 1
+fi
+CLUSTER_DNS="$(get_cluster_dns "$KUBECONFIG" "$CLUSTER_NAME")"
+if [[ -z "$CLUSTER_DNS" ]]; then
+  echo "CLUSTER_DNS not found in $KUBECONFIG under cluster name ${CLUSTER_NAME}."
+  exit 1
+fi
+export KUBECONFIG="$KUBECONFIG"
+kubectl config use-context admin
+oc config use-context admin
+if ! oc login -u admin -p $(cat "${ASSETS_DIR}/auth/kubeadmin-password"); then
+  echo "not logged in"
+fi
 
 TMP="$(mktemp -d)"
 trap_add_exit "rm -rf $TMP"
@@ -51,7 +66,7 @@ NAMESPACE="local"
 CATALOGSOURCE_FILE="${PKG_NAME}.catalogsource.yaml"
 SUBSCRIPTION_FILE="${PKG_NAME}.subscription.yaml"
 SC_PROXY_IMAGE="quay.io/operator-framework/scorecard-proxy:latest"
-OP_REGISTRY_IMAGE="quay.io/operatorframework/${PKG_NAME}:${OP_VER}-registry"
+OP_REGISTRY_IMAGE="quay.io/estroz/${PKG_NAME}:${OP_VER}-registry"
 SECRET_FILE="${TMP}/scorecard_secret.yaml"
 set -u
 CSV_FILE="$(find "$ABS_BUNDLE_PATH" -name "*.v${OP_VER}.clusterserviceversion.yaml" -print -quit)"
@@ -65,7 +80,8 @@ create_registry_dockerfile "Dockerfile" "$PKG_NAME"
 
 # Add scorecard proxy resources to the CSV.
 create_cr_files_from_metadata "$CSV_FILE" "$CR_DIR" "$NAMESPACE"
-create_kubeconfig_secret_file "$SECRET_FILE" "$NAMESPACE"
+create_permissions_files "$DEPLOY_DIR" "$CSV_FILE" "$PKG_NAME" "$NAMESPACE"
+create_kubeconfig_secret_file "$SECRET_FILE" "$NAMESPACE" "$CLUSTER_DNS"
 insert_kubeconfig_volume "$CSV_FILE"
 insert_kubeconfig_secret_mount "$CSV_FILE"
 insert_proxy_container "$CSV_FILE" "$SC_PROXY_IMAGE"
@@ -101,6 +117,8 @@ kubectl describe pods --namespace="$NAMESPACE" >> "$LOG_FILE" 2>&1
 trap "cat $LOG_FILE" ERR
 
 # Run scorecard tests on the operator.
+# TODO: run against multiple CR's. Right now the scorecard only works with one
+# CR.
 for cr_file in $(find "$CR_DIR" -name "*_cr.yaml" -print -quit); do
   operator-sdk scorecard \
     --cr-manifest "$cr_file" \
